# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/Timer.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_wBiosynthesisTimer(object):
    def setupUi(self, wBiosynthesisTimer):
        wBiosynthesisTimer.setObjectName("wBiosynthesisTimer")
        wBiosynthesisTimer.setWindowModality(QtCore.Qt.NonModal)
        wBiosynthesisTimer.resize(360, 300)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui/../../../../../.designer/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        wBiosynthesisTimer.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(wBiosynthesisTimer)
        self.centralwidget.setObjectName("centralwidget")
        self.gbManualMode = QtWidgets.QGroupBox(self.centralwidget)
        self.gbManualMode.setGeometry(QtCore.QRect(20, 142, 320, 150))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.gbManualMode.setFont(font)
        self.gbManualMode.setObjectName("gbManualMode")
        self.btnManualStop = QtWidgets.QPushButton(self.gbManualMode)
        self.btnManualStop.setGeometry(QtCore.QRect(10, 90, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.btnManualStop.setFont(font)
        self.btnManualStop.setObjectName("btnManualStop")
        self.btnManualStart = QtWidgets.QPushButton(self.gbManualMode)
        self.btnManualStart.setGeometry(QtCore.QRect(10, 40, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.btnManualStart.setFont(font)
        self.btnManualStart.setObjectName("btnManualStart")
        self.gbAutoMode = QtWidgets.QGroupBox(self.centralwidget)
        self.gbAutoMode.setEnabled(True)
        self.gbAutoMode.setGeometry(QtCore.QRect(20, 142, 320, 150))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.gbAutoMode.setFont(font)
        self.gbAutoMode.setObjectName("gbAutoMode")
        self.pbrProgressBar = QtWidgets.QProgressBar(self.gbAutoMode)
        self.pbrProgressBar.setGeometry(QtCore.QRect(10, 70, 300, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.pbrProgressBar.setFont(font)
        self.pbrProgressBar.setProperty("value", 0)
        self.pbrProgressBar.setObjectName("pbrProgressBar")
        self.btnAutoStart = QtWidgets.QPushButton(self.gbAutoMode)
        self.btnAutoStart.setGeometry(QtCore.QRect(10, 100, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.btnAutoStart.setFont(font)
        self.btnAutoStart.setObjectName("btnAutoStart")
        self.btnAutoStop = QtWidgets.QPushButton(self.gbAutoMode)
        self.btnAutoStop.setGeometry(QtCore.QRect(160, 100, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.btnAutoStop.setFont(font)
        self.btnAutoStop.setObjectName("btnAutoStop")
        self.lblTimer = QtWidgets.QLabel(self.gbAutoMode)
        self.lblTimer.setGeometry(QtCore.QRect(10, 29, 300, 31))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.lblTimer.setFont(font)
        self.lblTimer.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTimer.setObjectName("lblTimer")
        self.lblMode = QtWidgets.QLabel(self.centralwidget)
        self.lblMode.setGeometry(QtCore.QRect(20, 30, 80, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblMode.setFont(font)
        self.lblMode.setTextFormat(QtCore.Qt.AutoText)
        self.lblMode.setObjectName("lblMode")
        self.lblStatus = QtWidgets.QLabel(self.centralwidget)
        self.lblStatus.setGeometry(QtCore.QRect(20, 60, 80, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblStatus.setFont(font)
        self.lblStatus.setTextFormat(QtCore.Qt.AutoText)
        self.lblStatus.setObjectName("lblStatus")
        self.cmbCurrentMode = QtWidgets.QComboBox(self.centralwidget)
        self.cmbCurrentMode.setGeometry(QtCore.QRect(120, 30, 220, 25))
        self.cmbCurrentMode.setObjectName("cmbCurrentMode")
        self.cmbCurrentMode.addItem("")
        self.cmbCurrentMode.addItem("")
        self.txtCurrentStatus = QtWidgets.QLineEdit(self.centralwidget)
        self.txtCurrentStatus.setEnabled(True)
        self.txtCurrentStatus.setGeometry(QtCore.QRect(120, 60, 220, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtCurrentStatus.setFont(font)
        self.txtCurrentStatus.setReadOnly(True)
        self.txtCurrentStatus.setObjectName("txtCurrentStatus")
        wBiosynthesisTimer.setCentralWidget(self.centralwidget)

        self.retranslateUi(wBiosynthesisTimer)
        QtCore.QMetaObject.connectSlotsByName(wBiosynthesisTimer)

    def retranslateUi(self, wBiosynthesisTimer):
        _translate = QtCore.QCoreApplication.translate
        wBiosynthesisTimer.setWindowTitle(_translate("wBiosynthesisTimer", "БИОСИНТЕЗ - Таймер"))
        self.gbManualMode.setTitle(_translate("wBiosynthesisTimer", "Ручной режим"))
        self.btnManualStop.setText(_translate("wBiosynthesisTimer", "Выключить"))
        self.btnManualStart.setText(_translate("wBiosynthesisTimer", "Включить"))
        self.gbAutoMode.setTitle(_translate("wBiosynthesisTimer", "Автоматический режим"))
        self.btnAutoStart.setText(_translate("wBiosynthesisTimer", "Включить"))
        self.btnAutoStop.setText(_translate("wBiosynthesisTimer", "Выключить"))
        self.lblTimer.setText(_translate("wBiosynthesisTimer", "01:00"))
        self.lblMode.setText(_translate("wBiosynthesisTimer", "Режим: "))
        self.lblStatus.setText(_translate("wBiosynthesisTimer", "Статус:"))
        self.cmbCurrentMode.setItemText(0, _translate("wBiosynthesisTimer", "Ручной"))
        self.cmbCurrentMode.setItemText(1, _translate("wBiosynthesisTimer", "Автоматический"))
        self.txtCurrentStatus.setText(_translate("wBiosynthesisTimer", "клапан открыт"))
